Multiplayer code test.
capstone-projects-2024-fall/project-techtrek pull request #43
Opened 2024-11-20 15:31 UTC by IshanAgg125

Testing the code if multiple people can join the same room.

2024-11-20 19:55 UTC, Jericho-R-Orienza commented on devsdragons/package.json
do lines 25 and 26 not need commas?

2024-11-20 19:57 UTC, Jericho-R-Orienza requested changes
in package.json, do lines 25 and 26 need commas? Just double checking

2024-11-21 00:21 UTC, IshanAgg125 commented on devsdragons/package.json
just line 25

2024-11-21 01:00 UTC, AnimishTemple commented
Resolved merge conflicts, and will implement changes suggested by Jericho as we fixed that on local version of this branch already.

2024-11-21 05:51 UTC, Jericho-R-Orienza approved these changes

2024-11-22 16:46 UTC, AnimishTemple approved these changes
Nice!

2024-12-06 17:53 UTC, merged